---
- name: dotfiles | Find all files in the dotfiles directory
  ansible.builtin.find:
    paths: "{{ dotfiles_dir }}"
    recurse: true
    file_type: file
    hidden: true
  register: all_items

- name: dotfiles | Extract unique directories
  ansible.builtin.set_fact:
    unique_dirs: "{{ all_items.files | map(attribute='path') | map('dirname') | unique | list }}"

- name: dotfiles | Ensure parent directories exist
  ansible.builtin.file:
    path: "{{ home }}/{{ item | relpath(dotfiles_dir) }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: "0755"
  loop: "{{ unique_dirs }}"
  loop_control:
    label: "{{ item | relpath(dotfiles_dir) }}"

- name: dotfiles | Create symlinks for dotfiles
  ansible.builtin.file:
    src: "{{ item.path }}"
    dest: "{{ home }}/{{ item.path | relpath(dotfiles_dir) }}"
    state: link
    owner: "{{ user }}"
    group: "{{ group }}"
    follow: false
    force: true
  loop: "{{ all_items.files }}"
  when: item.path != dotfiles_dir
  loop_control:
    label: "{{ item.path | relpath(dotfiles_dir) }}"
