---
- name: Golang | Install Golang
  ansible.builtin.include_role:
    name: gantsign.golang

- name: Golang | Create Golang $GOPATH dir
  ansible.builtin.file:
    path: "{{ home }}/go"
    owner: "{{ user }}"
    group: "{{ group }}"
    state: directory
    mode: 0755

- name: Golang | Set Golang env vars in .profile
  ansible.builtin.blockinfile:
    path: "{{ home }}/.profile"
    block: |
      export GOPATH={{ home }}/go
      export PATH=$PATH:{{ ansible_local.golang.general.home }}/bin:$GOPATH/bin

- name: Golang | Install gopls
  become: false
  ansible.builtin.shell: >
    go install golang.org/x/tools/gopls@latest
  args:
    executable: /bin/bash
    chdir: "{{ home }}"
    creates: "{{ home }}/go/bin/gopls"
  environment:
    GOPATH: "{{ home }}/go"
    PATH: $PATH:{{ ansible_local.golang.general.home }}/bin:$GOPATH/bin

- name: Golang | Install golangci-lint-langserver
  become: false
  ansible.builtin.shell: >
    go install github.com/nametake/golangci-lint-langserver@latest
  args:
    executable: /bin/bash
    chdir: "{{ home }}"
    creates: "{{ home }}/go/bin/golangci-lint-langserver"
  environment:
    GOPATH: "{{ home }}/go"
    PATH: $PATH:{{ ansible_local.golang.general.home }}/bin:$GOPATH/bin

- name: Golang | Install Delve
  become: false
  ansible.builtin.shell: >
    go install github.com/go-delve/delve/cmd/dlv@latest
  args:
    executable: /bin/bash
    chdir: "{{ home }}"
    creates: "{{ home }}/go/bin/dlv"
  environment:
    GOPATH: "{{ home }}/go"
    PATH: $PATH:{{ ansible_local.golang.general.home }}/bin:$GOPATH/bin

- name: Golang | Install goimports
  become: false
  ansible.builtin.shell: >
    go install golang.org/x/tools/cmd/goimports@latest
  args:
    executable: /bin/bash
    chdir: "{{ home }}"
    creates: "{{ home }}/go/bin/goimports"
  environment:
    GOPATH: "{{ home }}/go"
    PATH: $PATH:{{ ansible_local.golang.general.home }}/bin:$GOPATH/bin
