---
- name: "Packages | Add Neovim PPA"
  ansible.builtin.apt_repository:
    repo: 'ppa:neovim-ppa/unstable'
    state: present

- name: "Packages | Add Helix PPA"
  ansible.builtin.apt_repository:
    repo: 'ppa:maveonair/helix-editor'
    state: present

- name: "Packages | Add Containerlab APT repo"
  ansible.builtin.apt_repository:
    repo: 'deb [trusted=yes] http://netdevops.fury.site/apt/ /'
    state: present
    filename: containerlab

- name: "Packages | Install packages"
  ansible.builtin.apt:
    update_cache: true
    name:
      - python3-pip
      - pipx
      - neovim
      - helix
      - fd-find
      - ripgrep
      - fzf
      - ipcalc
      - containerlab
    state: latest

- name: "Packages | Install gh"
  ansible.builtin.include_role:
    name: sgaunet.gh_role_installer
    vars_from: gh.yml

- name: "Packages | Install lazygit"
  ansible.builtin.include_role:
    name: sgaunet.gh_role_installer
    vars_from: lazygit.yml

- name: "Packages | Install pre-commit"
  ansible.builtin.include_role:
    name: sgaunet.gh_role_installer
    vars_from: pre-commit.yml

- name: "Packages | Install yazi"
  ansible.builtin.include_role:
    name: sgaunet.gh_role_installer
    vars_from: yazi.yml

- name: "Packages | Install zellij"
  ansible.builtin.include_role:
    name: sgaunet.gh_role_installer
    vars_from: zellij.yml
