---
- name: Python | Add ~/.local/bin to $PATH
  blockinfile:
    path: "{{ home }}/.profile"
    block: |
      export PATH=$PATH:{{ home }}/.local/bin

- name: Python | Install Poetry
  become: false
  community.general.pipx:
    name: poetry

- name: Python | Install Ruff
  become: false
  community.general.pipx:
    name: ruff

- name: Python | Install yamllint
  become: false
  community.general.pipx:
    name: yamllint
