---
- name: Install Poetry
  community.general.pipx:
    name: poetry
- name: Install Ruff
  community.general.pipx:
    name: ruff
- name: Install yamllint
  community.general.pipx:
    name: yamllint
